### ISSUE TITLE
install instructions [https://hiddentao.github.io/ansijet/] not working

### ISSUE THREAD

**Issue by bsdhsr** [hiddentao/ansijet#10] opened 2014-10-29 14:39 UTC
$ npm install
npm WARN deprecated gulp-clean@0.3.1: use gulp-rimraf instead

> v8flags@1.0.1 install /home/admin/ansijet/node_modules/gulp/node_modules/v8flags
> node fetch.js

flags for v8 3.26.33 cached.
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.11.14","npm":"2.0.0"})

> kerberos@0.0.3 install /home/admin/ansijet/node_modules/waigo-mongo/node_modules/koa-session-mongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/admin/ansijet/node_modules/waigo-mongo/node_modules/koa-session-mongo/node_modules/mongodb/node_modules/kerberos/build'
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  SOLINK_MODULE(target) Release/obj.target/kerberos.node: Finished
  COPY Release/kerberos.node
make: Leaving directory`/home/admin/ansijet/node_modules/waigo-mongo/node_modules/koa-session-mongo/node_modules/mongodb/node_modules/kerberos/build'
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.11.14","npm":"2.0.0"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.11.14","npm":"2.0.0"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.11.14","npm":"2.0.0"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.11.14","npm":"2.0.0"})
/

> kerberos@0.0.4 install /home/admin/ansijet/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/admin/ansijet/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  SOLINK_MODULE(target) Release/obj.target/kerberos.node: Finished
  COPY Release/kerberos.node
make: Leaving directory`/home/admin/ansijet/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'

> bson@0.2.5 install /home/admin/ansijet/node_modules/waigo-mongo/node_modules/koa-session-mongo/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/admin/ansijet/node_modules/waigo-mongo/node_modules/koa-session-mongo/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
make: Leaving directory`/home/admin/ansijet/node_modules/waigo-mongo/node_modules/koa-session-mongo/node_modules/mongodb/node_modules/bson/build'

> bson@0.2.15 install /home/admin/ansijet/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/admin/ansijet/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
  COPY Release/bson.node
make: Leaving directory`/home/admin/ansijet/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! path /home/admin/.npm/e484fccf-npm-gulp-util-2-2-20-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno -17

npm ERR! EEXIST, open '/home/admin/.npm/e484fccf-npm-gulp-util-2-2-20-package-tgz.lock'
File exists: /home/admin/.npm/e484fccf-npm-gulp-util-2-2-20-package-tgz.lock
Move it away, and try again. 
admin@ip-172-31-11-107:~/ansijet$ file /home/admin/.npm/e484fccf-npm-gulp-util-2-2-20-package-tgz.lock
/home/admin/.npm/e484fccf-npm-gulp-util-2-2-20-package-tgz.lock: ERROR: cannot open `/home/admin/.npm/e484fccf-npm-gulp-util-2-2-20-package-tgz.lock' (No such file or directory)

$ file /home/admin/.npm/e484fccf-npm-gulp-util-2-2-20-package-tgz.lock
/home/admin/.npm/e484fccf-npm-gulp-util-2-2-20-package-tgz.lock: ERROR: cannot open `/home/admin/.npm/e484fccf-npm-gulp-util-2-2-20-package-tgz.lock' (No such file or directory)

**Comment by hiddentao** [comment] 2014-11-03 15:56
Will look at this tomorrow.

**Comment by hiddentao** [comment] 2014-11-04 06:38
I am unable to reproduce this error. Am running in node 0.11.13 on OS X 10.10

**Comment by hiddentao** [comment] 2014-11-05 15:15
Have got it working on Ubuntu 14.04x64 with Node 0.11.13.

I've added `npm-shrinkwrap.json` to ensure that everyone all gets the known-to-work versions of each module.

**Comment by hiddentao** [comment] 2014-11-05 15:15
Sorry, closed by accident

**Comment by hiddentao** [comment] 2014-11-06 04:54
Have updated NPM shrinkwrap for 0.11.14.

**Comment by hiddentao** [comment] 2014-11-06 04:55
This should work ok now.

**Closed as completed by hiddentao** 2014-11-06 04:55 UTC
